name: Python Style Check

on: [push, pull_request]

jobs:
  style:
    name: Check Style
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'

      - name: Install Requirements
        run: pip install -r requirements.txt -r requirements-dev.txt

      - name: Check Style
        run: black dico
